### ISSUE TITLE
OUT_OF_MEMORY - line worker

### ISSUE THREAD

**Issue by mpatir** [caracal-pipeline/caracal#1412]
The line worker complains that it is out of memory and dies after about 2 mins. This occurs on ilifu even with allocated mem requirements of (which is too much for the line worker): 
#SBATCH --ntasks=1
#SBATCH --job-name='line'
#SBATCH --cpus-per-task=30
#SBATCH --mem=220
#SBATCH --time=48:00:00

The out of memory error seems to occur after calculating Doppler corrections. Is there a solution for this? Please see the log below: 

2022-03-11 19:45:31 CARACal INFO: obsconf: running
2022-03-11 19:45:31 CARACal INFO: obsconf: finished
2022-03-11 19:45:31 CARACal INFO: line: initializing
2022-03-11 19:45:31 CARACal INFO: MS #0: 1621019834_sub-J1430_p_0322-corr.ms
2022-03-11 19:45:31 CARACal INFO:   1 spectral windows, with NCHAN=1723
2022-03-11 19:45:31 CARACal INFO:   CHAN_FREQ from 1373993896.484375 Hz to 1418977783.203125 Hz with average channel width of 26123.046875 Hz
2022-03-11 19:45:31 CARACal INFO:   Target RA, Dec for Doppler correction: 217.600 deg, 3.370 deg
2022-03-11 19:45:33 CARACal INFO: Calculated common Doppler-corrected channel grid for all input .MS: 1721 channels starting at 1374061548.876Hz and with channel width 26123.836Hz.
2022-03-11 19:45:33 CARACal.Stimela.save-virgo_line_before-ms0 INFO: job started at 2022-03-11 19:45:33.752138
# WARNING: Overriding HOME environment variable with SINGULARITYENV_HOME is not permitted
# 2022-03-11 19:45:36: Initial memory state:
# 2022-03-11 19:45:36:               total        used        free      shared  buff/cache   available
# 2022-03-11 19:45:36: Mem:          236Gi       2.0Gi       232Gi       1.0Mi       1.4Gi       232Gi
# 2022-03-11 19:45:36: Swap:            0B          0B          0B
# 
/var/lib/slurm/slurmd/job2465698/slurm_script: line 14: 2346171 Killed                  caracal -c line.yml -ct singularity -sid /software/astro/caracal/STIMELA_IMAGES
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=2465698.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by paoloserra** [comment]
Can you post your config (at the top of the caracal log, so we see all settings)?

How large is your MS?

**Comment by paoloserra** [comment]
Can you post the settings as you see them in the log file, so we see all settings? Please use the "code" formatting as in my edits above, to make this easier to read. And which file is 516GB, the input one, the line file, before or after `mst`?

**Comment by mpatir** [comment]
Okay below is the entire log with input parameters. Excluding obsconfig things.
The 500GB is after transferring the model, before running transform in the line_worker. These data are from the 32k-mode so chanw ~ 5 km/s. 

'''
2022-03-11 19:48:39 CARACal INFO: Version 1.0.5 installed at /scratch3/users/mpati/caracal_venv3/lib/python3.9/site-packages/caracal
2022-03-11 19:48:39 CARACal INFO:
2022-03-11 19:48:39 CARACal INFO:   general:
2022-03-11 19:48:39 CARACal INFO:     title:                        ""
2022-03-11 19:48:39 CARACal INFO:     msdir:                        /idia/projects/virgofil/1621019834/msdir
2022-03-11 19:48:39 CARACal INFO:     rawdatadir:                   ""
2022-03-11 19:48:39 CARACal INFO:     input:                        /idia/projects/virgofil/1621019834/input
2022-03-11 19:48:39 CARACal INFO:     output:                       /idia/projects/virgofil/1621019834/output
2022-03-11 19:48:39 CARACal INFO:     prefix:                       virgo
2022-03-11 19:48:39 CARACal INFO:     prep_workspace:               True
2022-03-11 19:48:39 CARACal INFO:     init_notebooks:               std-progress-report, project-logs
2022-03-11 19:48:39 CARACal INFO:     report_notebooks:             [detailed-final-report]
2022-03-11 19:48:39 CARACal INFO:     final_report:                 False
2022-03-11 19:48:39 CARACal INFO:     backend:                      docker
2022-03-11 19:48:39 CARACal INFO:
2022-03-11 19:48:39 CARACal INFO:   getdata:
2022-03-11 19:48:39 CARACal INFO:     dataid:                       [1621019834_sub]
2022-03-11 19:48:39 CARACal INFO:     extension:                    ms
2022-03-11 19:48:39 CARACal INFO:     report:                       False
2022-03-11 19:48:39 CARACal INFO:     ignore_missing:               False
2022-03-11 19:48:39 CARACal INFO:
2022-03-11 19:48:39 CARACal INFO:   obsconf:
2022-03-11 19:48:39 CARACal INFO:     target:                       [all]
2022-03-11 19:48:39 CARACal INFO:     gcal:                         [all]
2022-03-11 19:48:39 CARACal INFO:     bpcal:                        [longest]
2022-03-11 19:48:39 CARACal INFO:     fcal:                         [longest]
2022-03-11 19:48:39 CARACal INFO:     xcal:                         [longest]
2022-03-11 19:48:39 CARACal INFO:     refant:                       0
2022-03-11 19:48:39 CARACal INFO:     maxdist:                      1000.0
2022-03-11 19:48:39 CARACal INFO:     minbase:                      150.0
2022-03-11 19:48:39 CARACal INFO:     report:                       False
2022-03-11 19:48:39 CARACal INFO:     obsinfo:
2022-03-11 19:48:39 CARACal INFO:       enable:                       True
2022-03-11 19:48:39 CARACal INFO:       listobs:                      True
2022-03-11 19:48:39 CARACal INFO:       summary_json:                 True
2022-03-11 19:48:39 CARACal INFO:       vampirisms:                   False
2022-03-11 19:48:39 CARACal INFO:       plotelev:
2022-03-11 19:48:39 CARACal INFO:         enable:                       True
2022-03-11 19:48:39 CARACal INFO:         plotter:                      owlcat


2022-03-11 19:48:39 CARACal INFO:   line:
2022-03-11 19:48:39 CARACal INFO:     enable:                       True
2022-03-11 19:48:39 CARACal INFO:     label_in:                     corr
2022-03-11 19:48:39 CARACal INFO:     line_name:                    lw0chansel
2022-03-11 19:48:39 CARACal INFO:     restfreq:                     1.420405752GHz
2022-03-11 19:48:39 CARACal INFO:     ncpu:                         0
2022-03-11 19:48:39 CARACal INFO:     overwrite_flagvers:           False
2022-03-11 19:48:39 CARACal INFO:     report:                       True
2022-03-11 19:48:39 CARACal INFO:     rewind_flags:
2022-03-11 19:48:39 CARACal INFO:       enable:                       True
2022-03-11 19:48:39 CARACal INFO:       mode:                         reset_worker
2022-03-11 19:48:39 CARACal INFO:       version:                      auto
2022-03-11 19:48:39 CARACal INFO:       mstransform_version:          auto
2022-03-11 19:48:39 CARACal INFO:     mstransform:
2022-03-11 19:48:39 CARACal INFO:       enable:                       True
2022-03-11 19:48:39 CARACal INFO:       col:                          corrected
2022-03-11 19:48:39 CARACal INFO:       obsinfo:                      True
2022-03-11 19:48:39 CARACal INFO:       doppler:
2022-03-11 19:48:39 CARACal INFO:         enable:                       True
2022-03-11 19:48:39 CARACal INFO:         telescope:                    meerkat
2022-03-11 19:48:39 CARACal INFO:         mode:                         frequency
2022-03-11 19:48:39 CARACal INFO:         frame:                        bary
2022-03-11 19:48:39 CARACal INFO:         veltype:                      radio
2022-03-11 19:48:39 CARACal INFO:         changrid:                     auto
2022-03-11 19:48:39 CARACal INFO:       uvlin:
2022-03-11 19:48:39 CARACal INFO:         enable:                       True
2022-03-11 19:48:39 CARACal INFO:         fitorder:                     3
2022-03-11 19:48:39 CARACal INFO:         fitspw:                       ""
2022-03-11 19:48:39 CARACal INFO:         exclude_known_sources:        False
2022-03-11 19:48:39 CARACal INFO:         known_sources_cat:            ""
2022-03-11 19:48:39 CARACal INFO:         known_sources_radius:         1.0
2022-03-11 19:48:39 CARACal INFO:         known_sources_flux:           0.0
2022-03-11 19:48:39 CARACal INFO:         known_sources_dv:             30.0
2022-03-11 19:48:39 CARACal INFO:     flag_mst_errors:
2022-03-11 19:48:39 CARACal INFO:       enable:                       True
2022-03-11 19:48:39 CARACal INFO:       strategy:                     postmst.rfis
2022-03-11 19:48:39 CARACal INFO:       readmode:                     auto
2022-03-11 19:48:39 CARACal INFO:     make_cube:
2022-03-11 19:48:39 CARACal INFO:       enable:                       True
2022-03-11 19:48:39 CARACal INFO:       image_with:                   wsclean
2022-03-11 19:48:39 CARACal INFO:       use_mstransform:              True
2022-03-11 19:48:39 CARACal INFO:       stokes:                       I
2022-03-11 19:48:39 CARACal INFO:       spwid:                        0
2022-03-11 19:48:39 CARACal INFO:       nchans:                       845
2022-03-11 19:48:39 CARACal INFO:       firstchan:                    876
2022-03-11 19:48:39 CARACal INFO:       binchans:                     1
2022-03-11 19:48:39 CARACal INFO:       npix:                         [1800]
2022-03-11 19:48:39 CARACal INFO:       cell:                         2.0
2022-03-11 19:48:39 CARACal INFO:       padding:                      1.2
2022-03-11 19:48:39 CARACal INFO:       weight:                       briggs
2022-03-11 19:48:39 CARACal INFO:       robust:                       0.5
2022-03-11 19:48:39 CARACal INFO:       taper:                        0.0
2022-03-11 19:48:39 CARACal INFO:       niter:                        1000000
2022-03-11 19:48:39 CARACal INFO:       gain:                         0.1
2022-03-11 19:48:39 CARACal INFO:       wscl_mgain:                   1.0
2022-03-11 19:48:39 CARACal INFO:       wscl_sofia_niter:             3
2022-03-11 19:48:39 CARACal INFO:       wscl_sofia_converge:          1.1
2022-03-11 19:48:39 CARACal INFO:       wscl_removeintermediate:      False
2022-03-11 19:48:39 CARACal INFO:       wscl_user_clean_mask:         ""
2022-03-11 19:48:39 CARACal INFO:       wscl_auto_mask:               10.0
2022-03-11 19:48:39 CARACal INFO:       wscl_auto_thr:                0.5
2022-03-11 19:48:39 CARACal INFO:       wscl_make_cube:               True
2022-03-11 19:48:39 CARACal INFO:       wscl_noupdatemod:             True
2022-03-11 19:48:39 CARACal INFO:       wscl_multiscale:              False
2022-03-11 19:48:39 CARACal INFO:       wscl_multiscale_scales:       ""
2022-03-11 19:48:39 CARACal INFO:       wscl_multiscale_bias:         0.6
2022-03-11 19:48:39 CARACal INFO:       wscl_nrdeconvsubimg:          0
2022-03-11 19:48:39 CARACal INFO:       wscl_beam:                    0, 0, 0
2022-03-11 19:48:39 CARACal INFO:       casa_thr:                     10mJy
2022-03-11 19:48:39 CARACal INFO:       casa_port2fits:               False
2022-03-11 19:48:39 CARACal INFO:     remove_stokes_axis:
2022-03-11 19:48:39 CARACal INFO:       enable:                       True
2022-03-11 19:48:39 CARACal INFO:     freq_to_vel:
2022-03-11 19:48:39 CARACal INFO:       enable:                       True
2022-03-11 19:48:39 CARACal INFO:       reverse:                      False
2022-03-11 19:48:39 CARACal INFO:     sofia:
2022-03-11 19:48:39 CARACal INFO:       enable:                       True
2022-03-11 19:48:39 CARACal INFO:       flag:                         False
2022-03-11 19:48:39 CARACal INFO:       flagregion:                   0, 0, 0, 0, 0, 0
2022-03-11 19:48:39 CARACal INFO:       rmsMode:                      mad
2022-03-11 19:48:39 CARACal INFO:       thr:                          4.0
2022-03-11 19:48:39 CARACal INFO:       merge:                        False
2022-03-11 19:48:39 CARACal INFO:       merge:                        False
2022-03-11 19:48:39 CARACal INFO:       mergeX:                       2
2022-03-11 19:48:39 CARACal INFO:       mergeY:                       2
2022-03-11 19:48:39 CARACal INFO:       mergeZ:                       3
2022-03-11 19:48:39 CARACal INFO:       minSizeX:                     3
2022-03-11 19:48:39 CARACal INFO:       minSizeY:                     3
2022-03-11 19:48:39 CARACal INFO:       minSizeZ:                     3
2022-03-11 19:48:39 CARACal INFO:       cubelets:                     True
2022-03-11 19:48:39 CARACal INFO:       mom0:                         True
2022-03-11 19:48:39 CARACal INFO:       mom1:                         True
2022-03-11 19:48:47 CARACal INFO: output directory for logs is /idia/projects/virgofil/1621019834/output/logs-20220311-194839
2022-03-11 19:48:47 CARACal INFO: /idia/projects/virgofil/1621019834/output/logs links to logs-20220311-194839
2022-03-11 19:48:47 CARACal INFO: /idia/projects/virgofil/1621019834/output/log-caracal.txt links to logs-20220311-194839/log-caracal.txt
2022-03-11 19:48:47 CARACal INFO: Copying MeerKAT input files into input folder
2022-03-11 19:48:47 CARACal INFO: Standard notebook /idia/projects/virgofil/1621019834/output/virgo-std-progress-report.ipynb already exists, won't overwrite
2022-03-11 19:48:47 CARACal INFO: Standard notebook /idia/projects/virgofil/1621019834/output/virgo-detailed-final-report.ipynb already exists, won't overwrite
2022-03-11 19:48:47 CARACal INFO: Standard notebook /idia/projects/virgofil/1621019834/output/virgo-project-logs.ipynb already exists, won't overwrite
2022-03-11 19:48:47 CARACal INFO: Saving original configuration file as /idia/projects/virgofil/1621019834/output/cfgFiles/line-20220311-194839.orig.yml
2022-03-11 19:48:48 CARACal INFO: Saving full configuration as /idia/projects/virgofil/1621019834/output/cfgFiles/line-20220311-194839.yml
2022-03-11 19:48:48 CARACal INFO: Configuring worker getdata
2022-03-11 19:48:48 CARACal INFO: Configuring worker obsconf
2022-03-11 19:48:48 CARACal INFO: Configuring worker line
2022-03-11 19:48:48 CARACal INFO: getdata: initializing
2022-03-11 19:48:48 CARACal INFO: getdata: running
2022-03-11 19:48:48 CARACal INFO: getdata: finished
2022-03-11 19:48:48 CARACal INFO: obsconf: initializing
2022-03-11 19:48:48 CARACal INFO: obsinfo file 1621019834_sub-obsinfo.txt exists, not regenerating
2022-03-11 19:48:48 CARACal INFO: summary file 1621019834_sub-summary.json exists, not regenerating
2022-03-11 19:48:48 CARACal INFO: elevation plot 1621019834_sub-elevation-tracks.png exists, not regenerating
2022-03-11 19:48:48 CARACal INFO: MS #0: 1621019834_sub.ms
2022-03-11 19:48:48 CARACal INFO:   1 spectral windows, with NCHAN=1723
2022-03-11 19:48:48 CARACal INFO:   CHAN_FREQ from 1373993896.484375 Hz to 1418977783.203125 Hz with average channel width of 26123.046875 Hz
2022-03-11 19:48:48 CARACal INFO:   target (TARGET):
2022-03-11 19:48:48 CARACal INFO:     J1430+0322 (ID=2) : 298.81 minutes | RA=217.60 deg, Dec=3.37 deg
2022-03-11 19:48:48 CARACal INFO:   gcal (CALIBRATE_AMPL,CALIBRATE_PHASE):
2022-03-11 19:48:48 CARACal INFO:     J1445+0958 (ID=1) : 7.86 minutes | RA=221.32 deg, Dec=9.98 deg
2022-03-11 19:48:48 CARACal INFO:   fcal (CALIBRATE_FLUX):
2022-03-11 19:48:48 CARACal INFO:     J1939-6342 (ID=0) : 19.86 minutes | RA=294.85 deg, Dec=-63.71 deg
2022-03-11 19:48:48 CARACal INFO:   bpcal (CALIBRATE_BANDPASS):
2022-03-11 19:48:48 CARACal INFO:     J1939-6342 (ID=0) : 19.86 minutes | RA=294.85 deg, Dec=-63.71 deg
2022-03-11 19:48:48 CARACal INFO: obsconf: running
2022-03-11 19:48:48 CARACal INFO: obsconf: finished
2022-03-11 19:48:48 CARACal INFO: line: initializing
2022-03-11 19:48:48 CARACal INFO: MS #0: 1621019834_sub-J1430_p_0322-corr.ms
2022-03-11 19:48:48 CARACal INFO:   1 spectral windows, with NCHAN=1723
2022-03-11 19:48:48 CARACal INFO:   CHAN_FREQ from 1373993896.484375 Hz to 1418977783.203125 Hz with average channel width of 26123.046875 Hz
2022-03-11 19:48:48 CARACal INFO:   Target RA, Dec for Doppler correction: 217.600 deg, 3.370 deg
2022-03-11 19:48:49 CARACal INFO: Calculated common Doppler-corrected channel grid for all input .MS: 1721 channels starting at 1374061548.876Hz and with channel width 26123.836Hz.
2022-03-11 19:48:49 CARACal.Stimela.save-virgo_line_before-ms0 INFO: job started at 2022-03-11 19:48:49.983010
# WARNING: Overriding HOME environment variable with SINGULARITYENV_HOME is not permitted
# 2022-03-11 19:48:51: Initial memory state:
# 2022-03-11 19:48:51:               total        used        free      shared  buff/cache   available
# 2022-03-11 19:48:51: Mem:          236Gi       2.0Gi       232Gi       1.0Mi       1.4Gi       232Gi
# 2022-03-11 19:48:51: Swap:            0B          0B          0B
# 
# =========================================
# The start-up time of CASA may vary
# depending on whether the shared libraries
# are cached or not.
# =========================================
# 
# Python: users/mpati^GIPython 5.1.0 -- An enhanced Interactive Python.
/var/lib/slurm/slurmd/job2465700/slurm_script: line 14: 2346488 Killed                  caracal -c line.yml -ct singularity -sid /software/astro/caracal/STIMELA_IMAGES
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=2465700.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
'''

**Comment by paoloserra** [comment]
The problem seems to be with saving the flag version `virgo_line_before`. It seems that the input MS (before running mstransform) is getting its flags saved to a new version. See this line in your log:
```
2022-03-11 19:48:49 CARACal.Stimela.save-virgo_line_before-ms0 INFO: job started at 2022-03-11 19:48:49.983010
```

This should happen in the following bit of the `line` worker:

https://github.com/caracal-pipeline/caracal/blob/83d919cd84101939abf101aa5c36559a1ee0e76f/caracal/workers/line_worker.py#L377-L414

Maybe you can do some debugging to understand exactly where the error is occurring?

There are two things I find puzzling:
1) saving a flag version shouldn't take all that RAM
2) I don't understand why the flag version is being saved in the first place. We had changed the CARACal flag version logic to avoid saving unnecessary flag versions, but it does not seem to be working here. Are you running CARACal master?

**Comment by mpatir** [comment]
> The problem seems to be with saving the flag version `virgo_line_before`. It seems that the input MS (before running mstransform) is getting its flags saved to a new version. See this line in your log:
> 
> ```
> 2022-03-11 19:48:49 CARACal.Stimela.save-virgo_line_before-ms0 INFO: job started at 2022-03-11 19:48:49.983010
> ```
> 
> This should happen in the following bit of the `line` worker:
> 
> https://github.com/caracal-pipeline/caracal/blob/83d919cd84101939abf101aa5c36559a1ee0e76f/caracal/workers/line_worker.py#L377-L414
> 
> 
> There are two things I find puzzling:
> 
>     1. saving a flag version shouldn't take all that RAM

Here I am not sure why these flags are taking so much RAM.

> 
>     2. I don't understand why the flag version is being saved in the first place. We had changed the CARACal flag version logic to avoid saving unnecessary flag versions, but it does not seem to be working here. Are you running CARACal master?

I think I know why. I am running version 1.0.5 I think from December or Jan. I see we are now on 1.0.6 and it seems the flag version logic thing was fixed in Feb?. I will try 1.0.6 and see if this resolves the issue.

> Maybe you can do some debugging to understand exactly where the error is occurring?

I will look into debugging to see what happened. Maybe getting 1.0.6 will solve this.

**Comment by paoloserra** [comment]
OK, 1.0.6 should do. It's probably still the same as master. Fingers crossed!

**Comment by mpatir** [comment]
Ok. I installed master which is basically 1.0.6. 

It seems the issue is more systemic. It might be specific to this data set since this did not happen with all other pointing ms of the same observation. 
It does not seem to matter where I start running the line worker it dies either way with this data set. E.g., I turned everything off except make cube and some other basic things (see below):

```
2022-03-14 23:55:55 CARACal INFO: Invoked as /scratch3/users/mpati/caracal_venv4/bin/caracal -c line.yml -ct singularity -sid /software/astro/caracal/STIMELA_IMAGES
2022-03-14 23:55:55 CARACal INFO: Loading pipeline configuration from line.yml
2022-03-14 23:55:56 CARACal INFO: Version 1.0.6 installed at /scratch3/users/mpati/caracal_venv4/lib/python3.9/site-packages/caracal
2022-03-14 23:55:56 CARACal INFO:
2022-03-14 23:55:56 CARACal INFO:   general:
2022-03-14 23:55:56 CARACal INFO:     title:                        ""
2022-03-14 23:55:56 CARACal INFO:     msdir:                        /idia/projects/virgofil/1621019834/msdir
2022-03-14 23:55:56 CARACal INFO:     rawdatadir:                   ""
2022-03-14 23:55:56 CARACal INFO:     input:                        /idia/projects/virgofil/1621019834/input
2022-03-14 23:55:56 CARACal INFO:     output:                       /idia/projects/virgofil/1621019834/output
2022-03-14 23:55:56 CARACal INFO:     prefix:                       virgo
2022-03-14 23:55:56 CARACal INFO:     prep_workspace:               True
2022-03-14 23:55:56 CARACal INFO:     init_notebooks:               std-progress-report, project-logs
2022-03-14 23:55:56 CARACal INFO:     report_notebooks:             [detailed-final-report]
2022-03-14 23:55:56 CARACal INFO:     final_report:                 False
2022-03-14 23:55:56 CARACal INFO:     backend:                      docker
2022-03-14 23:55:56 CARACal INFO:
2022-03-14 23:55:56 CARACal INFO:   getdata:
2022-03-14 23:55:56 CARACal INFO:     dataid:                       [1621019834_sub]
2022-03-14 23:55:56 CARACal INFO:     extension:                    ms
2022-03-14 23:55:56 CARACal INFO:     report:                       False
2022-03-14 23:55:56 CARACal INFO:     ignore_missing:               False
2022-03-14 23:55:56 CARACal INFO:
2022-03-14 23:55:56 CARACal INFO:   obsconf:
2022-03-14 23:55:56 CARACal INFO:     target:                       [all]
2022-03-14 23:55:56 CARACal INFO:     gcal:                         [all]
2022-03-14 23:55:56 CARACal INFO:     bpcal:                        [longest]
2022-03-14 23:55:56 CARACal INFO:     fcal:                         [longest]
2022-03-14 23:55:56 CARACal INFO:     xcal:                         [longest]
2022-03-14 23:55:56 CARACal INFO:     refant:                       0
2022-03-14 23:55:56 CARACal INFO:     maxdist:                      1000.0
2022-03-14 23:55:56 CARACal INFO:     minbase:                      150.0
2022-03-14 23:55:56 CARACal INFO:     report:                       False
2022-03-14 23:55:56 CARACal INFO:     obsinfo:
2022-03-14 23:55:56 CARACal INFO:       enable:                       True
2022-03-14 23:55:56 CARACal INFO:       listobs:                      True
2022-03-14 23:55:56 CARACal INFO:       summary_json:                 True
2022-03-14 23:55:56 CARACal INFO:       vampirisms:                   False
2022-03-14 23:55:56 CARACal INFO:       plotelev:
2022-03-14 23:55:56 CARACal INFO:         enable:                       True
2022-03-14 23:55:56 CARACal INFO:         plotter:                      owlcat
2022-03-14 23:55:56 CARACal INFO:
2022-03-14 23:55:56 CARACal INFO:   line:
2022-03-14 23:55:56 CARACal INFO:     enable:                       True
2022-03-14 23:55:56 CARACal INFO:     label_in:                     corr
2022-03-14 23:55:56 CARACal INFO:     line_name:                    lw0chansel
2022-03-14 23:55:56 CARACal INFO:     restfreq:                     1.420405752GHz
2022-03-14 23:55:56 CARACal INFO:     ncpu:                         0
2022-03-14 23:55:56 CARACal INFO:     overwrite_flagvers:           False
2022-03-14 23:55:56 CARACal INFO:     report:                       True
2022-03-14 23:55:56 CARACal INFO:     rewind_flags:
2022-03-14 23:55:56 CARACal INFO:       enable:                       True
2022-03-14 23:55:56 CARACal INFO:       mode:                         reset_worker
2022-03-14 23:55:56 CARACal INFO:       version:                      auto
2022-03-14 23:55:56 CARACal INFO:       mstransform_version:          auto
2022-03-14 23:55:56 CARACal INFO:     make_cube:
2022-03-14 23:55:56 CARACal INFO:       enable:                       True
2022-03-14 23:55:56 CARACal INFO:       image_with:                   wsclean
2022-03-14 23:55:56 CARACal INFO:       use_mstransform:              False
2022-03-14 23:55:56 CARACal INFO:       stokes:                       I
2022-03-14 23:55:56 CARACal INFO:       spwid:                        0
2022-03-14 23:55:56 CARACal INFO:       nchans:                       845
2022-03-14 23:55:56 CARACal INFO:       firstchan:                    876
2022-03-14 23:55:56 CARACal INFO:       binchans:                     1
2022-03-14 23:55:56 CARACal INFO:       npix:                         [1800]
2022-03-14 23:55:56 CARACal INFO:       cell:                         2.0
2022-03-14 23:55:56 CARACal INFO:       padding:                      1.2
2022-03-14 23:55:56 CARACal INFO:       weight:                       briggs
2022-03-14 23:55:56 CARACal INFO:       robust:                       0.5
2022-03-14 23:55:56 CARACal INFO:       taper:                        0.0
2022-03-14 23:55:56 CARACal INFO:       niter:                        1000000
2022-03-14 23:55:56 CARACal INFO:       gain:                         0.1
2022-03-14 23:55:56 CARACal INFO:       wscl_onlypsf:                 False
2022-03-14 23:55:56 CARACal INFO:       wscl_mgain:                   1.0
2022-03-14 23:55:56 CARACal INFO:       wscl_sofia_niter:             3
2022-03-14 23:55:56 CARACal INFO:       wscl_sofia_converge:          1.1
2022-03-14 23:55:56 CARACal INFO:       wscl_removeintermediate:      False
2022-03-14 23:55:56 CARACal INFO:       wscl_user_clean_mask:         ""
2022-03-14 23:55:56 CARACal INFO:       wscl_auto_mask:               10.0
2022-03-14 23:55:56 CARACal INFO:       wscl_auto_thr:                0.5
2022-03-14 23:55:56 CARACal INFO:       wscl_make_cube:               True
2022-03-14 23:55:56 CARACal INFO:       wscl_noupdatemod:             True
2022-03-14 23:55:56 CARACal INFO:       wscl_multiscale:              False
2022-03-14 23:55:56 CARACal INFO:       wscl_multiscale_scales:       ""
2022-03-14 23:55:56 CARACal INFO:       wscl_multiscale_bias:         0.6
2022-03-14 23:55:56 CARACal INFO:       wscl_nrdeconvsubimg:          1
2022-03-14 23:55:56 CARACal INFO:       wscl_beam:                    0.0, 0.0, 0.0
2022-03-14 23:55:56 CARACal INFO:       casa_thr:                     10mJy
2022-03-14 23:55:56 CARACal INFO:       casa_port2fits:               False
2022-03-14 23:55:56 CARACal INFO:     remove_stokes_axis:
2022-03-14 23:55:56 CARACal INFO:       enable:                       True
2022-03-14 23:55:56 CARACal INFO:     freq_to_vel:
2022-03-14 23:55:56 CARACal INFO:       enable:                       True
2022-03-14 23:55:56 CARACal INFO:       reverse:                      False
2022-03-14 23:55:56 CARACal INFO:     sofia:
2022-03-14 23:55:56 CARACal INFO:       enable:                       True
2022-03-14 23:55:56 CARACal INFO:       flag:                         False
2022-03-14 23:55:56 CARACal INFO:       flagregion:                   0, 0, 0, 0, 0, 0
2022-03-14 23:55:56 CARACal INFO:       rmsMode:                      mad
2022-03-14 23:55:56 CARACal INFO:       thr:                          4.0
2022-03-14 23:55:56 CARACal INFO:       merge:                        False
2022-03-14 23:55:56 CARACal INFO:       mergeX:                       2
2022-03-14 23:55:56 CARACal INFO:       mergeY:                       2
2022-03-14 23:55:56 CARACal INFO:       mergeZ:                       3
2022-03-14 23:55:56 CARACal INFO:       minSizeX:                     3
2022-03-14 23:55:56 CARACal INFO:       minSizeY:                     3
2022-03-14 23:55:56 CARACal INFO:       minSizeZ:                     3
2022-03-14 23:55:56 CARACal INFO:       cubelets:                     True
2022-03-14 23:55:56 CARACal INFO:       mom0:                         True
2022-03-14 23:55:56 CARACal INFO:       mom1:                         True
2022-03-14 23:56:04 CARACal INFO: output directory for logs is /idia/projects/virgofil/1621019834/output/logs-20220314-235556
2022-03-14 23:56:04 CARACal INFO: /idia/projects/virgofil/1621019834/output/logs links to logs-20220314-235556
2022-03-14 23:56:04 CARACal INFO: /idia/projects/virgofil/1621019834/output/log-caracal.txt links to logs-20220314-235556/log-caracal.txt
2022-03-14 23:56:04 CARACal INFO: Copying MeerKAT input files into input folder
2022-03-14 23:56:04 CARACal INFO: Standard notebook /idia/projects/virgofil/1621019834/output/virgo-std-progress-report.ipynb already exists, won't overwrite
2022-03-14 23:56:04 CARACal INFO: Standard notebook /idia/projects/virgofil/1621019834/output/virgo-project-logs.ipynb already exists, won't overwrite
2022-03-14 23:56:04 CARACal INFO: Standard notebook /idia/projects/virgofil/1621019834/output/virgo-detailed-final-report.ipynb already exists, won't overwrite
2022-03-14 23:56:04 CARACal INFO: Saving original configuration file as /idia/projects/virgofil/1621019834/output/cfgFiles/line-20220314-235556.orig.yml
2022-03-14 23:56:04 CARACal INFO: Saving full configuration as /idia/projects/virgofil/1621019834/output/cfgFiles/line-20220314-235556.yml
2022-03-14 23:56:04 CARACal INFO: Configuring worker getdata
2022-03-14 23:56:04 CARACal INFO: Configuring worker obsconf
2022-03-14 23:56:04 CARACal INFO: Configuring worker line
2022-03-14 23:56:04 CARACal INFO: getdata: initializing
2022-03-14 23:56:04 CARACal INFO: getdata: running
2022-03-14 23:56:04 CARACal INFO: getdata: finished
2022-03-14 23:56:04 CARACal INFO: obsconf: initializing
2022-03-14 23:56:04 CARACal INFO: obsinfo file 1621019834_sub-obsinfo.txt exists, not regenerating
2022-03-14 23:56:04 CARACal INFO: summary file 1621019834_sub-summary.json exists, not regenerating
2022-03-14 23:56:04 CARACal INFO: elevation plot 1621019834_sub-elevation-tracks.png exists, not regenerating
2022-03-14 23:56:04 CARACal INFO: MS #0: 1621019834_sub.ms
2022-03-14 23:56:05 CARACal INFO:   1 spectral windows, with NCHAN=1723
2022-03-14 23:56:05 CARACal INFO:   CHAN_FREQ from 1373993896.484375 Hz to 1418977783.203125 Hz with average channel width of 26123.046875 Hz
2022-03-14 23:56:05 CARACal INFO:   target (TARGET):
2022-03-14 23:56:05 CARACal INFO:     J1430+0322 (ID=2) : 298.81 minutes | RA=217.60 deg, Dec=3.37 deg
2022-03-14 23:56:05 CARACal INFO:   gcal (CALIBRATE_AMPL,CALIBRATE_PHASE):
2022-03-14 23:56:05 CARACal INFO:     J1445+0958 (ID=1) : 7.86 minutes | RA=221.32 deg, Dec=9.98 deg
2022-03-14 23:56:05 CARACal INFO:   fcal (CALIBRATE_FLUX):
2022-03-14 23:56:05 CARACal INFO:     J1939-6342 (ID=0) : 19.86 minutes | RA=294.85 deg, Dec=-63.71 deg
2022-03-14 23:56:05 CARACal INFO:   bpcal (CALIBRATE_BANDPASS):
2022-03-14 23:56:05 CARACal INFO:     J1939-6342 (ID=0) : 19.86 minutes | RA=294.85 deg, Dec=-63.71 deg
2022-03-14 23:56:05 CARACal INFO: obsconf: running
2022-03-14 23:56:05 CARACal INFO: line: initializing
2022-03-14 23:56:05 CARACal INFO: MS #0: 1621019834_sub-J1430_p_0322-corr.ms
2022-03-14 23:56:05 CARACal INFO:   1 spectral windows, with NCHAN=1723
2022-03-14 23:56:05 CARACal INFO:   CHAN_FREQ from 1373993896.484375 Hz to 1418977783.203125 Hz with average channel width of 26123.046875 Hz
2022-03-14 23:56:05 CARACal INFO:   Target RA, Dec for Doppler correction: 217.600 deg, 3.370 deg
2022-03-14 23:56:05 CARACal INFO: Collecting spectral info on MS files being imaged
2022-03-14 23:56:05 CARACal INFO: MS #0: 1621019834_sub-J1430_p_0322-corr.ms
2022-03-14 23:56:05 CARACal INFO:   1 spectral windows, with NCHAN=1723
2022-03-14 23:56:05 CARACal INFO:   The spectral reference frame is [5]
2022-03-14 23:56:05 CARACal INFO: Starting to make line cube for target J1430+0322
# INFO:    Using cached SIF image
2022-03-14 23:56:10 CARACal.Stimela.make_cube-lw0chansel-field0-iter1-with_automasking INFO: job started at 2022-03-14 23:56:10.360263
# WARNING: Overriding HOME environment variable with SINGULARITYENV_HOME is not permitted
# running WSClean: wsclean -name /stimela_mount/output/cubes/cube_1/virgo_J1430_p_0322_lw0chansel_1 -mem 100 -no-update-model-required -weight briggs 0.500 -taper-gaussian 0>
# 
# WSClean version 3.0.1 (2021-08-26)
# This software package is released under the GPL version 3.
# Author: André Offringa (offringa@gmail.com).
# 
# First measurement set has corrected data: tasks will be applied on the corrected data column.
# === IMAGING TABLE ===
#        # Pol Ch JG ²G FG FI In Freq(MHz)
# | Independent group:
# +-+-J- 0  I   0  0  0  0  0  0  1397-1397 (1)
# | Independent group:
# +-+-J- 1  I   1  1  1  1  0  0  1397-1397 (1)
# | Independent group:
...........

/var/lib/slurm/slurmd/job2468049/slurm_script: line 14: 1319773 Killed                  caracal -c line.yml -ct singularity -sid /software/astro/caracal/STIMELA_IMAGES
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=2468049.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

```

I will get into the code or look at my ms to see what is happening. I am leaving this issue open for now.

**Comment by paoloserra** [comment]
uh, ok, so now it died while imaging?? :(

**Comment by mpatir** [comment]
> 

Yep. Well, it is not just imaging. The line worker dies at basically every starting step. For example, if I switch on subtract model it dies there too with the same "out of memory" error message. So wherever it has to start working it dies.

**Comment by IanHeywood** [comment]
Coupling `#SBATCH --mem=220` with `-mem 100` in the wsclean call might be the problem. wsclean will look at the memory on the node, think it has access to 256 GB, try to use that amount and then will get promptly killed by the slurm controller. You can try dropping `-mem` to 220/256 = 85 and see if that fixes it.

**Comment by mpatir** [comment]
@paoloserra and @IanHeywood . Thank you both very much for looking into this issue. 

I could kick myself right now. It appears I was asking for 220 bytes (see first text in the thread) and not 220GB in my sbatch settings. Simply changing this bit from ``` #SBATCH --mem=220 ``` to ``` #SBATCH --mem=220GB ``` solved the issue. 

I have also lowered the memory requirement to 85*GB* so avoid running into the memory issue with wsclean.

A week was spent on this issue on my side and I was just missing units. *sigh.  

Resolved. I will close the issue now.
